version: '3.8'
services:
  postgresql:
    image: postgres:13
    # volumes:
    #     - ./pgdata/:/var/lib/postgresql/data/
    environment:
      # - POSTGRES_DB=innovds
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
